CS3620_Portfolio/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('PortfolioDatabase/', include('PortfolioDatabase.urls'))
]

PortfolioDatabase/urls.py
from . import views
from django.urls import path

app_name = 'PortfolioDatabase'
urlpatterns = [
    path('home/', views.home, name="home"),
    path('hobbies/', views.hobbies, name="hobbies"),
    path('portfolio/', views.portfolio, name="portfolio"),
    path('contact/', views.contact, name="contact"),
    path('hobbies/<int:hobby_id>', views.hobby_detail, name="hobby_details"),
    path('portfolio/<int:portfolio_id>', views.portfolio_detail, name="portfolio_details"),
]

PortfolioDatabase/models.py
from django.db import models

# Create your models here.
class Hobby(models.Model):
    name = models.CharField(max_length = 100)
    description = models.TextField(max_length = 400)
    image = models.CharField(max_length = 500, default = 'https://upload.wikimedia.org/wikipedia/commons/1/14/No_Image_Available.jpg?20200913095930')

    def __str__(self):
        return self.name
    
class Portfolio(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(max_length=400)
    image = models.CharField(max_length = 500, default = 'https://upload.wikimedia.org/wikipedia/commons/1/14/No_Image_Available.jpg?20200913095930')

    def __str__(self):
        return self.name

PortfolioDatabase/views.py
from django.shortcuts import render
from django.shortcuts import HttpResponse
from .models import Hobby, Portfolio
from django.template import loader

# Create your views here.
def home(request):
    context = {}
    return render(request, 'index.html', context)
def hobbies(request):
    hobby_list = Hobby.objects.all()
    context = {
        'hobby_list' : hobby_list,
    }
    return render(request, 'hobbies.html', context)

def portfolio(request):
    portfolio_list = Portfolio.objects.all()
    context = {
        'portfolio_list' : portfolio_list,
    }
    return render(request, 'portfolio.html', context)

def contact(request):
    context = {}
    return render(request, 'contact.html', context)

def hobby_detail(request, hobby_id):
    hobby = Hobby.objects.get(pk=hobby_id)
    context = {
        'hobby' : hobby,
    }
    return render(request, 'hobby_details.html', context)

def portfolio_detail(request, portfolio_id):
    portfolio = Portfolio.objects.get(pk=portfolio_id)
    context = {
        'portfolio' : portfolio,
    }
    return render(request, 'portfolio_details.html', context)

PortfolioDatabase/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'styles.css' %}"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
    <title></title>
</head>
<body>
    <div class="nav-container">
        <nav class="navbar navbar-dark bg-dark">
            <a class="navbar-brand" id="watermark" href="#">Portfolio Site</a>
            <a class="nav-link text-light" id="link" aria-current="page" href="/PortfolioDatabase/home">HOME</a>
            <a class="nav-link text-light" id="link" href="/PortfolioDatabase/hobbies">HOBBIES</a>
            <a class="nav-link text-light" id="link" href="/PortfolioDatabase/portfolio">PORTFOLIO</a>
            <a class="nav-link text-light" id="link" href="/PortfolioDatabase/contact">CONTACT</a>
        </nav>
    </div>
    <div class="content">

        {% block body %}
        {% endblock %}

    </div>
</body>
</html>

PortfolioDatabase/templates/contact.html
{% extends './base.html' %}

    {% block body %}
    <h3>aritaylor@mail.weber.edu</h3>
    {% endblock %}

PortfolioDatabase/templates/hobbies.html
{% extends './base.html' %}

    {% block body %}
    <ul>
        {% for hobby in hobby_list %}
        <div class="row row-container">
            <div class="col-md-3 offset-md-2">
                <h3>{{ hobby.name }}</h3>
            </div>
            <div class="col-md-5 offset-md-2">
                <a href="{% url 'PortfolioDatabase:hobby_details' hobby.id %}" class="btn btn-success">Details</a>
            </div>
        </div>
        {% endfor %}
    </ul>
    {% endblock %}

PortfolioDatabase/templates/hobby_details.html
{% extends './base.html' %}

{% block body %}
<div class="container">
    <div class="row row-container">
        <div class="col-md-2 col-container">
            <img class="card" src="{{hobby.image}}">
        </div>
        <div class="col-md-6 col-container">
            <h1 class="title">{{hobby.name}}</h1>
            <h2>{{hobby.description}}</h2>
        </div>
        <div class="col-md-4 btn-container col-container">
            <a href="{% url 'PortfolioDatabase:hobbies' %}" class="btn btn-success">Back</a>
        </div>
    </div>
    
</div>
    
{% endblock %}

PortfolioDatabase/templates/index.html
{% extends './base.html' %}

    {% block body %}
    <h1>Welcome to Ari Taylor's Portfolio Database!</h1>
    <h3>I am a computer science student at Weber State University.</h3>
    {% endblock %}

PortfolioDatabase/templates/portfolio.html
{% extends './base.html' %}

    {% block body %}
    {% for portfolio in portfolio_list %}
        <div class="row row-container">
            <div class="col-md-3 offset-md-2">
                <h3>{{ portfolio.name }}</h3>
            </div>
            <div class="col-md-5 offset-md-2">
                <a href="{% url 'PortfolioDatabase:portfolio_details' portfolio.id %}" class="btn btn-success">Details</a>
            </div>
        </div>
        {% endfor %}
    {% endblock %}

PortfolioDatabase/templates/portfolio_details.html
{% extends './base.html' %}

{% block body %}
<div class="container">
    <div class="row row-container">
        <div class="col-md-2 col-container">
            <img class="card" src="{{portfolio.image}}">
        </div>
        <div class="col-md-6 col-container">
            <h1 class="title">{{portfolio.name}}</h1>
            <h2>{{portfolio.description}}</h2>
        </div>
        <div class="col-md-4 btn-container col-container">
            <a href="{% url 'PortfolioDatabase:portfolio' %}" class="btn btn-success">Back</a>
        </div>
    </div>
    
</div>
    
{% endblock %}